### ISSUE TITLE
Whats about the OperationContract annotation

### ISSUE THREAD

**Issue by Flaflo** [thinktecture/blazor-wasm-grpc-code-first#1]
I was taking a look at the gRPC Service interfaces and wondered why there were no [OperationContract] annotations. Are they not required?

(https://docs.microsoft.com/de-de/dotnet/api/system.servicemodel.operationcontractattribute?view=dotnet-plat-ext-5.0)

**Comment by Flaflo** [comment]
Or maybe I am mixing something up with the WCF Annotations?

**Comment by ChristianWeyer** [comment]
You don't need the OC.
